In [1]:
#importing libraries
import pandas as pd
import sqlite3
import statistics

In [2]:
#fetching csv file with pandas data frame
df = pd.read_csv("gobankingrates.csv")

In [3]:
df

,city_name,city_median,city_homeowner,city_renter
0,"Albuquerque, New Mexico","Median income: $53,936","Income needed if you’re a homeowner: $81,526.74","Income needed if you’re a renter: $65,446.74"
1,"Arlington, Texas","Median income: $63,351","Income needed if you’re a homeowner: $88,313.93","Income needed if you’re a renter: $76,697.93"
2,"Atlanta, Georgia","Median income: $64,179","Income needed if you’re a homeowner: $99,084.11","Income needed if you’re a renter: $80,820.11"
3,"Austin, Texas","Median income: $75,752","Income needed if you’re a homeowner: $135,709.07","Income needed if you’re a renter: $60,565.07"
4,"Baltimore, Maryland","Median income: $52,164","Income needed if you’re a homeowner: $67,888.98","Income needed if you’re a renter: $81,592.98"
5,"Boston, Massachusetts","Median income: $76,298","Income needed if you’re a homeowner: $153,953.52","Income needed if you’re a renter: $87,065.52"
6,"Charlotte, North Carolina","Median income: $65,359","Income needed if you’re a homeowner: $98,104.67","Income needed if you’re a renter: $65,992.67"
7,"Chicago, Illinois","Median income: $62,097","Income needed if you’re a homeowner: $85,326.41","Income needed if you’re a renter: $75,702.41"
8,"Colorado Springs, Colorado","Median income: $67,719","Income needed if you’re a homeowner: $109,836.72","Income needed if you’re a renter: $86,676.72"
9,"Columbus, Ohio","Median income: $54,902","Income needed if you’re a homeowner: $71,807.21","Income needed if you’re a renter: $71,519.21"
10,"Dallas, Texas","Median income: $54,747","Income needed if you’re a homeowner: $87,816.30","Income needed if you’re a renter: $69,216.30"
11,"Denver, Colorado","Median income: $72,661","Income needed if you’re a homeowner: $135,814.29","Income needed if you’re a renter: $87,382.29"
12,"Detroit, Michigan","Median income: $32,498","Income needed if you’re a homeowner: $126,960.75","Income needed if you’re a renter: $72,528.75"
13,"El Paso, Texas","Median income: $48,866","Income needed if you’re a homeowner: $64,270.19","Income needed if you’re a renter: $70,270.19"
14,"Fort Worth, Texas","Median income: $64,567","Income needed if you’re a homeowner: $87,581.69","Income needed if you’re a renter: $84,461.69"
15,"Fresno, California","Median income: $53,368","Income needed if you’re a homeowner: $94,566.58","Income needed if you’re a renter: $70,614.58"
16,"Houston, Texas","Median income: $53,600","Income needed if you’re a homeowner: $77,835.84","Income needed if you’re a renter: $63,363.84"
17,"Indianapolis, Indiana","Median income: $50,813","Income needed if you’re a homeowner: $67,865.41","Income needed if you’re a renter: $67,889.41"
18,"Jacksonville, Florida","Median income: $55,531","Income needed if you’re a homeowner: $84,560.93","Income needed if you’re a renter: $62,696.93"
19,"Kansas City, Missouri","Median income: $56,179","Income needed if you’re a homeowner: $70,142.35","Income needed if you’re a renter: $66,446.35"
20,"Las Vegas, Nevada","Median income: $58,377","Income needed if you’re a homeowner: $106,227.90","Income needed if you’re a renter: $77,643.90"
21,"Long Beach, California","Median income: $66,410","Income needed if you’re a homeowner: $164,797.88","Income needed if you’re a renter: $78,709.88"
22,"Los Angeles, California","Median income: $65,290","Income needed if you’re a homeowner: $191,142.92","Income needed if you’re a renter: $83,238.92"
23,"Louisville, Kentucky","Median income: $54,929","Income needed if you’re a homeowner: $69,624.19","Income needed if you’re a renter: $62,832.19"
24,"Memphis, Tennessee","Median income: $41,864","Income needed if you’re a homeowner: $58,358.33","Income needed if you’re a renter: $70,430.33"
25,"Mesa, Arizona","Median income: $61,640","Income needed if you’re a homeowner: $103,611.43","Income needed if you’re a renter: $72,075.43"
26,"Miami, Florida","Median income: $44,268","Income needed if you’re a homeowner: $126,270.90","Income needed if you’re a renter: $79,254.90"
27,"Milwaukee, Wisconsin","Median income: $43,125","Income needed if you’re a homeowner: $63,842.13","Income needed if you’re a renter: $59,282.13"
28,"Minneapolis, Minnesota","Median income: $66,068","Income needed if you’re a homeowner: $86,546.52","Income needed if you’re a renter: $59,666.52"
29,"Nashville, Tennessee","Median income: $62,087","Income needed if you’re a homeowner: $108,095.81","Income needed if you’re a renter: $84,935.81"
30,"New Orleans, Louisiana","Median income: $43,258","Income needed if you’re a homeowner: $79,515.42","Income needed if you’re a renter: $63,555.42"
31,"New York City, New York","Median income: $67,046","Income needed if you’re a homeowner: $169,886.32","Income needed if you’re a renter: $76,574.32"
32,"Oakland, California","Median income: $80,143","Income needed if you’re a homeowner: $188,336.51","Income needed if you’re a renter: $77,648.51"
33,"Oklahoma City, Oklahoma","Median income: $56,456","Income needed if you’re a homeowner: $59,019.10","Income needed if you’re a renter: $62,691.10"
34,"Omaha, Nebraska","Median income: $62,213","Income needed if you’re a homeowner: $79,736.46","Income needed if you’re a renter: $78,680.46"
35,"Philadelphia, Pennsylvania","Median income: $49,127","Income needed if you’re a homeowner: $105,641.63","Income needed if you’re a renter: $66,713.63"
36,"Phoenix, Arizona","Median income: $60,914","Income needed if you’re a homeowner: $72,816.33","Income needed if you’re a renter: $71,280.33"
37,"Portland, Oregon","Median income: $73,159","Income needed if you’re a homeowner: $125,792.86","Income needed if you’re a renter: $78,896.86"
38,"Raleigh, North Carolina","Median income: $69,720","Income needed if you’re a homeowner: $106,104.82","Income needed if you’re a renter: $72,000.82"
39,"Sacramento, California","Median income: $65,847","Income needed if you’re a homeowner: $115,849.90","Income needed if you’re a renter: $87,625.90"
40,"San Antonio, Texas","Median income: $53,420","Income needed if you’re a homeowner: $80,437.74","Income needed if you’re a renter: $60,109.74"
41,"San Diego, California","Median income: $83,454","Income needed if you’re a homeowner: $189,391.69","Income needed if you’re a renter: $86,359.69"
42,"San Francisco, California","Median income: $119,136","Income needed if you’re a homeowner: $282,493.95","Income needed if you’re a renter: $98,509.95"
43,"San Jose, California","Median income: $117,324","Income needed if you’re a homeowner: $258,137.21","Income needed if you’re a renter: $93,977.21"
44,"Seattle, Washington","Median income: $97,185","Income needed if you’re a homeowner: $183,084.12","Income needed if you’re a renter: $76,260.12"
45,"Tampa, Florida","Median income: $55,634","Income needed if you’re a homeowner: $102,525.56","Income needed if you’re a renter: $69,597.56"
46,"Tucson, Arizona","Median income: $45,227","Income needed if you’re a homeowner: $84,669.97","Income needed if you’re a renter: $62,805.97"
47,"Tulsa, Oklahoma","Median income: $49,474","Income needed if you’re a homeowner: $64,564.24","Income needed if you’re a renter: $78,916.24"
48,"Virginia Beach, Virgina","Median income: $78,136","Income needed if you’re a homeowner: $95,518.17","Income needed if you’re a renter: $76,414.17"
49,"Washington, D.C.","Median Income: $90,842","Income needed if you’re a homeowner: $97,458.34","Income needed if you’re a renter: $93,978.34"

In [4]:
#connecting to sqlite3
conn = sqlite3.connect("database.db")
#making df into sql table
df.to_sql("city_table", conn, if_exists="replace")

In [5]:
#readjusting df variable to return all columns from city_table
df = pd.read_sql_query("SELECT * FROM city_table", conn)

In [6]:
#checking to see if it worked
df

,index,city_name,city_median,city_homeowner,city_renter
0,0,"Albuquerque, New Mexico","Median income: $53,936","Income needed if you’re a homeowner: $81,526.74","Income needed if you’re a renter: $65,446.74"
1,1,"Arlington, Texas","Median income: $63,351","Income needed if you’re a homeowner: $88,313.93","Income needed if you’re a renter: $76,697.93"
2,2,"Atlanta, Georgia","Median income: $64,179","Income needed if you’re a homeowner: $99,084.11","Income needed if you’re a renter: $80,820.11"
3,3,"Austin, Texas","Median income: $75,752","Income needed if you’re a homeowner: $135,709.07","Income needed if you’re a renter: $60,565.07"
4,4,"Baltimore, Maryland","Median income: $52,164","Income needed if you’re a homeowner: $67,888.98","Income needed if you’re a renter: $81,592.98"
5,5,"Boston, Massachusetts","Median income: $76,298","Income needed if you’re a homeowner: $153,953.52","Income needed if you’re a renter: $87,065.52"
6,6,"Charlotte, North Carolina","Median income: $65,359","Income needed if you’re a homeowner: $98,104.67","Income needed if you’re a renter: $65,992.67"
7,7,"Chicago, Illinois","Median income: $62,097","Income needed if you’re a homeowner: $85,326.41","Income needed if you’re a renter: $75,702.41"
8,8,"Colorado Springs, Colorado","Median income: $67,719","Income needed if you’re a homeowner: $109,836.72","Income needed if you’re a renter: $86,676.72"
9,9,"Columbus, Ohio","Median income: $54,902","Income needed if you’re a homeowner: $71,807.21","Income needed if you’re a renter: $71,519.21"
10,10,"Dallas, Texas","Median income: $54,747","Income needed if you’re a homeowner: $87,816.30","Income needed if you’re a renter: $69,216.30"
11,11,"Denver, Colorado","Median income: $72,661","Income needed if you’re a homeowner: $135,814.29","Income needed if you’re a renter: $87,382.29"
12,12,"Detroit, Michigan","Median income: $32,498","Income needed if you’re a homeowner: $126,960.75","Income needed if you’re a renter: $72,528.75"
13,13,"El Paso, Texas","Median income: $48,866","Income needed if you’re a homeowner: $64,270.19","Income needed if you’re a renter: $70,270.19"
14,14,"Fort Worth, Texas","Median income: $64,567","Income needed if you’re a homeowner: $87,581.69","Income needed if you’re a renter: $84,461.69"
15,15,"Fresno, California","Median income: $53,368","Income needed if you’re a homeowner: $94,566.58","Income needed if you’re a renter: $70,614.58"
16,16,"Houston, Texas","Median income: $53,600","Income needed if you’re a homeowner: $77,835.84","Income needed if you’re a renter: $63,363.84"
17,17,"Indianapolis, Indiana","Median income: $50,813","Income needed if you’re a homeowner: $67,865.41","Income needed if you’re a renter: $67,889.41"
18,18,"Jacksonville, Florida","Median income: $55,531","Income needed if you’re a homeowner: $84,560.93","Income needed if you’re a renter: $62,696.93"
19,19,"Kansas City, Missouri","Median income: $56,179","Income needed if you’re a homeowner: $70,142.35","Income needed if you’re a renter: $66,446.35"
20,20,"Las Vegas, Nevada","Median income: $58,377","Income needed if you’re a homeowner: $106,227.90","Income needed if you’re a renter: $77,643.90"
21,21,"Long Beach, California","Median income: $66,410","Income needed if you’re a homeowner: $164,797.88","Income needed if you’re a renter: $78,709.88"
22,22,"Los Angeles, California","Median income: $65,290","Income needed if you’re a homeowner: $191,142.92","Income needed if you’re a renter: $83,238.92"
23,23,"Louisville, Kentucky","Median income: $54,929","Income needed if you’re a homeowner: $69,624.19","Income needed if you’re a renter: $62,832.19"
24,24,"Memphis, Tennessee","Median income: $41,864","Income needed if you’re a homeowner: $58,358.33","Income needed if you’re a renter: $70,430.33"
25,25,"Mesa, Arizona","Median income: $61,640","Income needed if you’re a homeowner: $103,611.43","Income needed if you’re a renter: $72,075.43"
26,26,"Miami, Florida","Median income: $44,268","Income needed if you’re a homeowner: $126,270.90","Income needed if you’re a renter: $79,254.90"
27,27,"Milwaukee, Wisconsin","Median income: $43,125","Income needed if you’re a homeowner: $63,842.13","Income needed if you’re a renter: $59,282.13"
28,28,"Minneapolis, Minnesota","Median income: $66,068","Income needed if you’re a homeowner: $86,546.52","Income needed if you’re a renter: $59,666.52"
29,29,"Nashville, Tennessee","Median income: $62,087","Income needed if you’re a homeowner: $108,095.81","Income needed if you’re a renter: $84,935.81"
30,30,"New Orleans, Louisiana","Median income: $43,258","Income needed if you’re a homeowner: $79,515.42","Income needed if you’re a renter: $63,555.42"
31,31,"New York City, New York","Median income: $67,046","Income needed if you’re a homeowner: $169,886.32","Income needed if you’re a renter: $76,574.32"
32,32,"Oakland, California","Median income: $80,143","Income needed if you’re a homeowner: $188,336.51","Income needed if you’re a renter: $77,648.51"
33,33,"Oklahoma City, Oklahoma","Median income: $56,456","Income needed if you’re a homeowner: $59,019.10","Income needed if you’re a renter: $62,691.10"
34,34,"Omaha, Nebraska","Median income: $62,213","Income needed if you’re a homeowner: $79,736.46","Income needed if you’re a renter: $78,680.46"
35,35,"Philadelphia, Pennsylvania","Median income: $49,127","Income needed if you’re a homeowner: $105,641.63","Income needed if you’re a renter: $66,713.63"
36,36,"Phoenix, Arizona","Median income: $60,914","Income needed if you’re a homeowner: $72,816.33","Income needed if you’re a renter: $71,280.33"
37,37,"Portland, Oregon","Median income: $73,159","Income needed if you’re a homeowner: $125,792.86","Income needed if you’re a renter: $78,896.86"
38,38,"Raleigh, North Carolina","Median income: $69,720","Income needed if you’re a homeowner: $106,104.82","Income needed if you’re a renter: $72,000.82"
39,39,"Sacramento, California","Median income: $65,847","Income needed if you’re a homeowner: $115,849.90","Income needed if you’re a renter: $87,625.90"
40,40,"San Antonio, Texas","Median income: $53,420","Income needed if you’re a homeowner: $80,437.74","Income needed if you’re a renter: $60,109.74"
41,41,"San Diego, California","Median income: $83,454","Income needed if you’re a homeowner: $189,391.69","Income needed if you’re a renter: $86,359.69"
42,42,"San Francisco, California","Median income: $119,136","Income needed if you’re a homeowner: $282,493.95","Income needed if you’re a renter: $98,509.95"
43,43,"San Jose, California","Median income: $117,324","Income needed if you’re a homeowner: $258,137.21","Income needed if you’re a renter: $93,977.21"
44,44,"Seattle, Washington","Median income: $97,185","Income needed if you’re a homeowner: $183,084.12","Income needed if you’re a renter: $76,260.12"
45,45,"Tampa, Florida","Median income: $55,634","Income needed if you’re a homeowner: $102,525.56","Income needed if you’re a renter: $69,597.56"
46,46,"Tucson, Arizona","Median income: $45,227","Income needed if you’re a homeowner: $84,669.97","Income needed if you’re a renter: $62,805.97"
47,47,"Tulsa, Oklahoma","Median income: $49,474","Income needed if you’re a homeowner: $64,564.24","Income needed if you’re a renter: $78,916.24"
48,48,"Virginia Beach, Virgina","Median income: $78,136","Income needed if you’re a homeowner: $95,518.17","Income needed if you’re a renter: $76,414.17"
49,49,"Washington, D.C.","Median Income: $90,842","Income needed if you’re a homeowner: $97,458.34","Income needed if you’re a renter: $93,978.34"

In [7]:
#returning all data types
print(df.dtypes)

index              int64
city_name         object
city_median       object
city_homeowner    object
city_renter       object
dtype: object

In [8]:
#making city_homeowner column into a list
s = df['city_homeowner'].tolist()

In [9]:
s

['Income needed if you’re a homeowner: $81,526.74',
 'Income needed if you’re a homeowner: $88,313.93',
 'Income needed if you’re a homeowner: $99,084.11',
 'Income needed if you’re a homeowner: $135,709.07',
 'Income needed if you’re a homeowner: $67,888.98',
 'Income needed if you’re a homeowner: $153,953.52',
 'Income needed if you’re a homeowner: $98,104.67',
 'Income needed if you’re a homeowner: $85,326.41',
 'Income needed if you’re a homeowner: $109,836.72',
 'Income needed if you’re a homeowner: $71,807.21',
 'Income needed if you’re a homeowner: $87,816.30',
 'Income needed if you’re a homeowner: $135,814.29',
 'Income needed if you’re a homeowner: $126,960.75',
 'Income needed if you’re a homeowner: $64,270.19',
 'Income needed if you’re a homeowner: $87,581.69',
 'Income needed if you’re a homeowner: $94,566.58',
 'Income needed if you’re a homeowner: $77,835.84',
 'Income needed if you’re a homeowner: $67,865.41',
 'Income needed if you’re a homeowner: $84,560.93',
 'Income needed if you’re a homeowner: $70,142.35',
 'Income needed if you’re a homeowner: $106,227.90',
 'Income needed if you’re a homeowner: $164,797.88',
 'Income needed if you’re a homeowner: $191,142.92',
 'Income needed if you’re a homeowner: $69,624.19',
 'Income needed if you’re a homeowner: $58,358.33',
 'Income needed if you’re a homeowner: $103,611.43',
 'Income needed if you’re a homeowner: $126,270.90',
 'Income needed if you’re a homeowner: $63,842.13',
 'Income needed if you’re a homeowner: $86,546.52',
 'Income needed if you’re a homeowner: $108,095.81',
 'Income needed if you’re a homeowner: $79,515.42',
 'Income needed if you’re a homeowner: $169,886.32',
 'Income needed if you’re a homeowner: $188,336.51',
 'Income needed if you’re a homeowner: $59,019.10',
 'Income needed if you’re a homeowner: $79,736.46',
 'Income needed if you’re a homeowner: $105,641.63',
 'Income needed if you’re a homeowner: $72,816.33',
 'Income needed if you’re a homeowner: $125,792.86',
 'Income needed if you’re a homeowner: $106,104.82',
 'Income needed if you’re a homeowner: $115,849.90',
 'Income needed if you’re a homeowner: $80,437.74',
 'Income needed if you’re a homeowner: $189,391.69',
 'Income needed if you’re a homeowner: $282,493.95',
 'Income needed if you’re a homeowner: $258,137.21',
 'Income needed if you’re a homeowner: $183,084.12',
 'Income needed if you’re a homeowner: $102,525.56',
 'Income needed if you’re a homeowner: $84,669.97',
 'Income needed if you’re a homeowner: $64,564.24',
 'Income needed if you’re a homeowner: $95,518.17',
 'Income needed if you’re a homeowner: $97,458.34']

In [10]:
#extracting all the number values from the list
values = []

for v in s:
    
    num = v[-10:]
    
    values.append(num)

In [11]:
values

['$81,526.74',
 '$88,313.93',
 '$99,084.11',
 '135,709.07',
 '$67,888.98',
 '153,953.52',
 '$98,104.67',
 '$85,326.41',
 '109,836.72',
 '$71,807.21',
 '$87,816.30',
 '135,814.29',
 '126,960.75',
 '$64,270.19',
 '$87,581.69',
 '$94,566.58',
 '$77,835.84',
 '$67,865.41',
 '$84,560.93',
 '$70,142.35',
 '106,227.90',
 '164,797.88',
 '191,142.92',
 '$69,624.19',
 '$58,358.33',
 '103,611.43',
 '126,270.90',
 '$63,842.13',
 '$86,546.52',
 '108,095.81',
 '$79,515.42',
 '169,886.32',
 '188,336.51',
 '$59,019.10',
 '$79,736.46',
 '105,641.63',
 '$72,816.33',
 '125,792.86',
 '106,104.82',
 '115,849.90',
 '$80,437.74',
 '189,391.69',
 '282,493.95',
 '258,137.21',
 '183,084.12',
 '102,525.56',
 '$84,669.97',
 '$64,564.24',
 '$95,518.17',
 '$97,458.34']

In [12]:
#removing "$" and "," so that i can convert each value into a float
home_owner = []

for v in values:
    
    
    s = v.replace("$", "").replace(",", "")
        
    float_value = float(s)
    
    home_owner.append(float_value)

In [13]:
home_owner

[81526.74,
 88313.93,
 99084.11,
 135709.07,
 67888.98,
 153953.52,
 98104.67,
 85326.41,
 109836.72,
 71807.21,
 87816.3,
 135814.29,
 126960.75,
 64270.19,
 87581.69,
 94566.58,
 77835.84,
 67865.41,
 84560.93,
 70142.35,
 106227.9,
 164797.88,
 191142.92,
 69624.19,
 58358.33,
 103611.43,
 126270.9,
 63842.13,
 86546.52,
 108095.81,
 79515.42,
 169886.32,
 188336.51,
 59019.1,
 79736.46,
 105641.63,
 72816.33,
 125792.86,
 106104.82,
 115849.9,
 80437.74,
 189391.69,
 282493.95,
 258137.21,
 183084.12,
 102525.56,
 84669.97,
 64564.24,
 95518.17,
 97458.34]

In [14]:
#now that every value is a float i can find the average
average = statistics.mean(home_owner)

In [15]:
average

110169.28080000001

In [16]:
#returning all the values that are below the average and adding "$" and "," back into each value
new_list_h = [format("${:,.2f}".format(value)) for value in home_owner if value < average]

In [17]:
#converting each value into string
ch = []

for v in new_list_h:
    
    s_value = str(v)
    
    ch.append(s_value)

In [18]:
ch

['$81,526.74',
 '$88,313.93',
 '$99,084.11',
 '$67,888.98',
 '$98,104.67',
 '$85,326.41',
 '$109,836.72',
 '$71,807.21',
 '$87,816.30',
 '$64,270.19',
 '$87,581.69',
 '$94,566.58',
 '$77,835.84',
 '$67,865.41',
 '$84,560.93',
 '$70,142.35',
 '$106,227.90',
 '$69,624.19',
 '$58,358.33',
 '$103,611.43',
 '$63,842.13',
 '$86,546.52',
 '$108,095.81',
 '$79,515.42',
 '$59,019.10',
 '$79,736.46',
 '$105,641.63',
 '$72,816.33',
 '$106,104.82',
 '$80,437.74',
 '$102,525.56',
 '$84,669.97',
 '$64,564.24',
 '$95,518.17',
 '$97,458.34']

In [19]:
#adding proper format for each value
for i in range(len(ch)):
    ch[i] = "Income needed if you’re a homeowner: " + ch[i]

In [20]:
ch

['Income needed if you’re a homeowner: $81,526.74',
 'Income needed if you’re a homeowner: $88,313.93',
 'Income needed if you’re a homeowner: $99,084.11',
 'Income needed if you’re a homeowner: $67,888.98',
 'Income needed if you’re a homeowner: $98,104.67',
 'Income needed if you’re a homeowner: $85,326.41',
 'Income needed if you’re a homeowner: $109,836.72',
 'Income needed if you’re a homeowner: $71,807.21',
 'Income needed if you’re a homeowner: $87,816.30',
 'Income needed if you’re a homeowner: $64,270.19',
 'Income needed if you’re a homeowner: $87,581.69',
 'Income needed if you’re a homeowner: $94,566.58',
 'Income needed if you’re a homeowner: $77,835.84',
 'Income needed if you’re a homeowner: $67,865.41',
 'Income needed if you’re a homeowner: $84,560.93',
 'Income needed if you’re a homeowner: $70,142.35',
 'Income needed if you’re a homeowner: $106,227.90',
 'Income needed if you’re a homeowner: $69,624.19',
 'Income needed if you’re a homeowner: $58,358.33',
 'Income needed if you’re a homeowner: $103,611.43',
 'Income needed if you’re a homeowner: $63,842.13',
 'Income needed if you’re a homeowner: $86,546.52',
 'Income needed if you’re a homeowner: $108,095.81',
 'Income needed if you’re a homeowner: $79,515.42',
 'Income needed if you’re a homeowner: $59,019.10',
 'Income needed if you’re a homeowner: $79,736.46',
 'Income needed if you’re a homeowner: $105,641.63',
 'Income needed if you’re a homeowner: $72,816.33',
 'Income needed if you’re a homeowner: $106,104.82',
 'Income needed if you’re a homeowner: $80,437.74',
 'Income needed if you’re a homeowner: $102,525.56',
 'Income needed if you’re a homeowner: $84,669.97',
 'Income needed if you’re a homeowner: $64,564.24',
 'Income needed if you’re a homeowner: $95,518.17',
 'Income needed if you’re a homeowner: $97,458.34']

In [21]:
#creating a query that returns each value of my ch list
query_1 = "SELECT * FROM city_table WHERE city_homeowner IN ({})".format(', '.join(['?' for x in ch]))

d = pd.read_sql_query(query_1, conn, params=ch)

In [22]:
d

,index,city_name,city_median,city_homeowner,city_renter
0,0,"Albuquerque, New Mexico","Median income: $53,936","Income needed if you’re a homeowner: $81,526.74","Income needed if you’re a renter: $65,446.74"
1,1,"Arlington, Texas","Median income: $63,351","Income needed if you’re a homeowner: $88,313.93","Income needed if you’re a renter: $76,697.93"
2,2,"Atlanta, Georgia","Median income: $64,179","Income needed if you’re a homeowner: $99,084.11","Income needed if you’re a renter: $80,820.11"
3,4,"Baltimore, Maryland","Median income: $52,164","Income needed if you’re a homeowner: $67,888.98","Income needed if you’re a renter: $81,592.98"
4,6,"Charlotte, North Carolina","Median income: $65,359","Income needed if you’re a homeowner: $98,104.67","Income needed if you’re a renter: $65,992.67"
5,7,"Chicago, Illinois","Median income: $62,097","Income needed if you’re a homeowner: $85,326.41","Income needed if you’re a renter: $75,702.41"
6,8,"Colorado Springs, Colorado","Median income: $67,719","Income needed if you’re a homeowner: $109,836.72","Income needed if you’re a renter: $86,676.72"
7,9,"Columbus, Ohio","Median income: $54,902","Income needed if you’re a homeowner: $71,807.21","Income needed if you’re a renter: $71,519.21"
8,10,"Dallas, Texas","Median income: $54,747","Income needed if you’re a homeowner: $87,816.30","Income needed if you’re a renter: $69,216.30"
9,13,"El Paso, Texas","Median income: $48,866","Income needed if you’re a homeowner: $64,270.19","Income needed if you’re a renter: $70,270.19"
10,14,"Fort Worth, Texas","Median income: $64,567","Income needed if you’re a homeowner: $87,581.69","Income needed if you’re a renter: $84,461.69"
11,15,"Fresno, California","Median income: $53,368","Income needed if you’re a homeowner: $94,566.58","Income needed if you’re a renter: $70,614.58"
12,16,"Houston, Texas","Median income: $53,600","Income needed if you’re a homeowner: $77,835.84","Income needed if you’re a renter: $63,363.84"
13,17,"Indianapolis, Indiana","Median income: $50,813","Income needed if you’re a homeowner: $67,865.41","Income needed if you’re a renter: $67,889.41"
14,18,"Jacksonville, Florida","Median income: $55,531","Income needed if you’re a homeowner: $84,560.93","Income needed if you’re a renter: $62,696.93"
15,19,"Kansas City, Missouri","Median income: $56,179","Income needed if you’re a homeowner: $70,142.35","Income needed if you’re a renter: $66,446.35"
16,20,"Las Vegas, Nevada","Median income: $58,377","Income needed if you’re a homeowner: $106,227.90","Income needed if you’re a renter: $77,643.90"
17,23,"Louisville, Kentucky","Median income: $54,929","Income needed if you’re a homeowner: $69,624.19","Income needed if you’re a renter: $62,832.19"
18,24,"Memphis, Tennessee","Median income: $41,864","Income needed if you’re a homeowner: $58,358.33","Income needed if you’re a renter: $70,430.33"
19,25,"Mesa, Arizona","Median income: $61,640","Income needed if you’re a homeowner: $103,611.43","Income needed if you’re a renter: $72,075.43"
20,27,"Milwaukee, Wisconsin","Median income: $43,125","Income needed if you’re a homeowner: $63,842.13","Income needed if you’re a renter: $59,282.13"
21,28,"Minneapolis, Minnesota","Median income: $66,068","Income needed if you’re a homeowner: $86,546.52","Income needed if you’re a renter: $59,666.52"
22,29,"Nashville, Tennessee","Median income: $62,087","Income needed if you’re a homeowner: $108,095.81","Income needed if you’re a renter: $84,935.81"
23,30,"New Orleans, Louisiana","Median income: $43,258","Income needed if you’re a homeowner: $79,515.42","Income needed if you’re a renter: $63,555.42"
24,33,"Oklahoma City, Oklahoma","Median income: $56,456","Income needed if you’re a homeowner: $59,019.10","Income needed if you’re a renter: $62,691.10"
25,34,"Omaha, Nebraska","Median income: $62,213","Income needed if you’re a homeowner: $79,736.46","Income needed if you’re a renter: $78,680.46"
26,35,"Philadelphia, Pennsylvania","Median income: $49,127","Income needed if you’re a homeowner: $105,641.63","Income needed if you’re a renter: $66,713.63"
27,36,"Phoenix, Arizona","Median income: $60,914","Income needed if you’re a homeowner: $72,816.33","Income needed if you’re a renter: $71,280.33"
28,38,"Raleigh, North Carolina","Median income: $69,720","Income needed if you’re a homeowner: $106,104.82","Income needed if you’re a renter: $72,000.82"
29,40,"San Antonio, Texas","Median income: $53,420","Income needed if you’re a homeowner: $80,437.74","Income needed if you’re a renter: $60,109.74"
30,45,"Tampa, Florida","Median income: $55,634","Income needed if you’re a homeowner: $102,525.56","Income needed if you’re a renter: $69,597.56"
31,46,"Tucson, Arizona","Median income: $45,227","Income needed if you’re a homeowner: $84,669.97","Income needed if you’re a renter: $62,805.97"
32,47,"Tulsa, Oklahoma","Median income: $49,474","Income needed if you’re a homeowner: $64,564.24","Income needed if you’re a renter: $78,916.24"
33,48,"Virginia Beach, Virgina","Median income: $78,136","Income needed if you’re a homeowner: $95,518.17","Income needed if you’re a renter: $76,414.17"
34,49,"Washington, D.C.","Median Income: $90,842","Income needed if you’re a homeowner: $97,458.34","Income needed if you’re a renter: $93,978.34"

In [23]:
#converting 'city_renter' into a list
string = df['city_renter'].tolist()

In [24]:
#extracting all the number values from the list
r_values = []

for v in string:
    
    num = v[-10:]
    
    r_values.append(num)

In [25]:
r_values

['$65,446.74',
 '$76,697.93',
 '$80,820.11',
 '$60,565.07',
 '$81,592.98',
 '$87,065.52',
 '$65,992.67',
 '$75,702.41',
 '$86,676.72',
 '$71,519.21',
 '$69,216.30',
 '$87,382.29',
 '$72,528.75',
 '$70,270.19',
 '$84,461.69',
 '$70,614.58',
 '$63,363.84',
 '$67,889.41',
 '$62,696.93',
 '$66,446.35',
 '$77,643.90',
 '$78,709.88',
 '$83,238.92',
 '$62,832.19',
 '$70,430.33',
 '$72,075.43',
 '$79,254.90',
 '$59,282.13',
 '$59,666.52',
 '$84,935.81',
 '$63,555.42',
 '$76,574.32',
 '$77,648.51',
 '$62,691.10',
 '$78,680.46',
 '$66,713.63',
 '$71,280.33',
 '$78,896.86',
 '$72,000.82',
 '$87,625.90',
 '$60,109.74',
 '$86,359.69',
 '$98,509.95',
 '$93,977.21',
 '$76,260.12',
 '$69,597.56',
 '$62,805.97',
 '$78,916.24',
 '$76,414.17',
 '$93,978.34']

In [26]:
#removing "$" and "," so that i can convert each value into a float
renter = []

for v in r_values:
    
    
    s = v.replace("$", "").replace(",", "")
        
    float_value = float(s)
    
    renter.append(float_value)

In [27]:
renter

[65446.74,
 76697.93,
 80820.11,
 60565.07,
 81592.98,
 87065.52,
 65992.67,
 75702.41,
 86676.72,
 71519.21,
 69216.3,
 87382.29,
 72528.75,
 70270.19,
 84461.69,
 70614.58,
 63363.84,
 67889.41,
 62696.93,
 66446.35,
 77643.9,
 78709.88,
 83238.92,
 62832.19,
 70430.33,
 72075.43,
 79254.9,
 59282.13,
 59666.52,
 84935.81,
 63555.42,
 76574.32,
 77648.51,
 62691.1,
 78680.46,
 66713.63,
 71280.33,
 78896.86,
 72000.82,
 87625.9,
 60109.74,
 86359.69,
 98509.95,
 93977.21,
 76260.12,
 69597.56,
 62805.97,
 78916.24,
 76414.17,
 93978.34]

In [28]:
#now that every value is a float i can find the average
average_2 = statistics.mean(renter)

In [29]:
average_2

74552.3208

In [30]:
#returning all values below average and re inserting "$" and "," to each value 
new_list_r = [format("${:,.2f}".format(num)) for num in renter if num < average_2]

In [31]:
#converting each value into a string
rh = []

for r in new_list_r:
    
    r_value = str(r)
    
    rh.append(r_value)

In [32]:
rh

['$65,446.74',
 '$60,565.07',
 '$65,992.67',
 '$71,519.21',
 '$69,216.30',
 '$72,528.75',
 '$70,270.19',
 '$70,614.58',
 '$63,363.84',
 '$67,889.41',
 '$62,696.93',
 '$66,446.35',
 '$62,832.19',
 '$70,430.33',
 '$72,075.43',
 '$59,282.13',
 '$59,666.52',
 '$63,555.42',
 '$62,691.10',
 '$66,713.63',
 '$71,280.33',
 '$72,000.82',
 '$60,109.74',
 '$69,597.56',
 '$62,805.97']

In [33]:
#using for loop to add proper format to each value 
for i in range(len(rh)):
    rh[i] = "Income needed if you’re a renter: " + rh[i]

In [34]:
rh

['Income needed if you’re a renter: $65,446.74',
 'Income needed if you’re a renter: $60,565.07',
 'Income needed if you’re a renter: $65,992.67',
 'Income needed if you’re a renter: $71,519.21',
 'Income needed if you’re a renter: $69,216.30',
 'Income needed if you’re a renter: $72,528.75',
 'Income needed if you’re a renter: $70,270.19',
 'Income needed if you’re a renter: $70,614.58',
 'Income needed if you’re a renter: $63,363.84',
 'Income needed if you’re a renter: $67,889.41',
 'Income needed if you’re a renter: $62,696.93',
 'Income needed if you’re a renter: $66,446.35',
 'Income needed if you’re a renter: $62,832.19',
 'Income needed if you’re a renter: $70,430.33',
 'Income needed if you’re a renter: $72,075.43',
 'Income needed if you’re a renter: $59,282.13',
 'Income needed if you’re a renter: $59,666.52',
 'Income needed if you’re a renter: $63,555.42',
 'Income needed if you’re a renter: $62,691.10',
 'Income needed if you’re a renter: $66,713.63',
 'Income needed if you’re a renter: $71,280.33',
 'Income needed if you’re a renter: $72,000.82',
 'Income needed if you’re a renter: $60,109.74',
 'Income needed if you’re a renter: $69,597.56',
 'Income needed if you’re a renter: $62,805.97']

In [35]:
#creating a query that returns each value from my rh list
query_2 = "SELECT * FROM city_table WHERE city_renter IN ({})".format(", ".join(["?" for x in rh]))

renter_d = pd.read_sql_query(query_2, conn, params=rh)

In [36]:
renter_d

,index,city_name,city_median,city_homeowner,city_renter
0,0,"Albuquerque, New Mexico","Median income: $53,936","Income needed if you’re a homeowner: $81,526.74","Income needed if you’re a renter: $65,446.74"
1,3,"Austin, Texas","Median income: $75,752","Income needed if you’re a homeowner: $135,709.07","Income needed if you’re a renter: $60,565.07"
2,6,"Charlotte, North Carolina","Median income: $65,359","Income needed if you’re a homeowner: $98,104.67","Income needed if you’re a renter: $65,992.67"
3,9,"Columbus, Ohio","Median income: $54,902","Income needed if you’re a homeowner: $71,807.21","Income needed if you’re a renter: $71,519.21"
4,10,"Dallas, Texas","Median income: $54,747","Income needed if you’re a homeowner: $87,816.30","Income needed if you’re a renter: $69,216.30"
5,12,"Detroit, Michigan","Median income: $32,498","Income needed if you’re a homeowner: $126,960.75","Income needed if you’re a renter: $72,528.75"
6,13,"El Paso, Texas","Median income: $48,866","Income needed if you’re a homeowner: $64,270.19","Income needed if you’re a renter: $70,270.19"
7,15,"Fresno, California","Median income: $53,368","Income needed if you’re a homeowner: $94,566.58","Income needed if you’re a renter: $70,614.58"
8,16,"Houston, Texas","Median income: $53,600","Income needed if you’re a homeowner: $77,835.84","Income needed if you’re a renter: $63,363.84"
9,17,"Indianapolis, Indiana","Median income: $50,813","Income needed if you’re a homeowner: $67,865.41","Income needed if you’re a renter: $67,889.41"
10,18,"Jacksonville, Florida","Median income: $55,531","Income needed if you’re a homeowner: $84,560.93","Income needed if you’re a renter: $62,696.93"
11,19,"Kansas City, Missouri","Median income: $56,179","Income needed if you’re a homeowner: $70,142.35","Income needed if you’re a renter: $66,446.35"
12,23,"Louisville, Kentucky","Median income: $54,929","Income needed if you’re a homeowner: $69,624.19","Income needed if you’re a renter: $62,832.19"
13,24,"Memphis, Tennessee","Median income: $41,864","Income needed if you’re a homeowner: $58,358.33","Income needed if you’re a renter: $70,430.33"
14,25,"Mesa, Arizona","Median income: $61,640","Income needed if you’re a homeowner: $103,611.43","Income needed if you’re a renter: $72,075.43"
15,27,"Milwaukee, Wisconsin","Median income: $43,125","Income needed if you’re a homeowner: $63,842.13","Income needed if you’re a renter: $59,282.13"
16,28,"Minneapolis, Minnesota","Median income: $66,068","Income needed if you’re a homeowner: $86,546.52","Income needed if you’re a renter: $59,666.52"
17,30,"New Orleans, Louisiana","Median income: $43,258","Income needed if you’re a homeowner: $79,515.42","Income needed if you’re a renter: $63,555.42"
18,33,"Oklahoma City, Oklahoma","Median income: $56,456","Income needed if you’re a homeowner: $59,019.10","Income needed if you’re a renter: $62,691.10"
19,35,"Philadelphia, Pennsylvania","Median income: $49,127","Income needed if you’re a homeowner: $105,641.63","Income needed if you’re a renter: $66,713.63"
20,36,"Phoenix, Arizona","Median income: $60,914","Income needed if you’re a homeowner: $72,816.33","Income needed if you’re a renter: $71,280.33"
21,38,"Raleigh, North Carolina","Median income: $69,720","Income needed if you’re a homeowner: $106,104.82","Income needed if you’re a renter: $72,000.82"
22,40,"San Antonio, Texas","Median income: $53,420","Income needed if you’re a homeowner: $80,437.74","Income needed if you’re a renter: $60,109.74"
23,45,"Tampa, Florida","Median income: $55,634","Income needed if you’re a homeowner: $102,525.56","Income needed if you’re a renter: $69,597.56"
24,46,"Tucson, Arizona","Median income: $45,227","Income needed if you’re a homeowner: $84,669.97","Income needed if you’re a renter: $62,805.97"

In [37]:
d

,index,city_name,city_median,city_homeowner,city_renter
0,0,"Albuquerque, New Mexico","Median income: $53,936","Income needed if you’re a homeowner: $81,526.74","Income needed if you’re a renter: $65,446.74"
1,1,"Arlington, Texas","Median income: $63,351","Income needed if you’re a homeowner: $88,313.93","Income needed if you’re a renter: $76,697.93"
2,2,"Atlanta, Georgia","Median income: $64,179","Income needed if you’re a homeowner: $99,084.11","Income needed if you’re a renter: $80,820.11"
3,4,"Baltimore, Maryland","Median income: $52,164","Income needed if you’re a homeowner: $67,888.98","Income needed if you’re a renter: $81,592.98"
4,6,"Charlotte, North Carolina","Median income: $65,359","Income needed if you’re a homeowner: $98,104.67","Income needed if you’re a renter: $65,992.67"
5,7,"Chicago, Illinois","Median income: $62,097","Income needed if you’re a homeowner: $85,326.41","Income needed if you’re a renter: $75,702.41"
6,8,"Colorado Springs, Colorado","Median income: $67,719","Income needed if you’re a homeowner: $109,836.72","Income needed if you’re a renter: $86,676.72"
7,9,"Columbus, Ohio","Median income: $54,902","Income needed if you’re a homeowner: $71,807.21","Income needed if you’re a renter: $71,519.21"
8,10,"Dallas, Texas","Median income: $54,747","Income needed if you’re a homeowner: $87,816.30","Income needed if you’re a renter: $69,216.30"
9,13,"El Paso, Texas","Median income: $48,866","Income needed if you’re a homeowner: $64,270.19","Income needed if you’re a renter: $70,270.19"
10,14,"Fort Worth, Texas","Median income: $64,567","Income needed if you’re a homeowner: $87,581.69","Income needed if you’re a renter: $84,461.69"
11,15,"Fresno, California","Median income: $53,368","Income needed if you’re a homeowner: $94,566.58","Income needed if you’re a renter: $70,614.58"
12,16,"Houston, Texas","Median income: $53,600","Income needed if you’re a homeowner: $77,835.84","Income needed if you’re a renter: $63,363.84"
13,17,"Indianapolis, Indiana","Median income: $50,813","Income needed if you’re a homeowner: $67,865.41","Income needed if you’re a renter: $67,889.41"
14,18,"Jacksonville, Florida","Median income: $55,531","Income needed if you’re a homeowner: $84,560.93","Income needed if you’re a renter: $62,696.93"
15,19,"Kansas City, Missouri","Median income: $56,179","Income needed if you’re a homeowner: $70,142.35","Income needed if you’re a renter: $66,446.35"
16,20,"Las Vegas, Nevada","Median income: $58,377","Income needed if you’re a homeowner: $106,227.90","Income needed if you’re a renter: $77,643.90"
17,23,"Louisville, Kentucky","Median income: $54,929","Income needed if you’re a homeowner: $69,624.19","Income needed if you’re a renter: $62,832.19"
18,24,"Memphis, Tennessee","Median income: $41,864","Income needed if you’re a homeowner: $58,358.33","Income needed if you’re a renter: $70,430.33"
19,25,"Mesa, Arizona","Median income: $61,640","Income needed if you’re a homeowner: $103,611.43","Income needed if you’re a renter: $72,075.43"
20,27,"Milwaukee, Wisconsin","Median income: $43,125","Income needed if you’re a homeowner: $63,842.13","Income needed if you’re a renter: $59,282.13"
21,28,"Minneapolis, Minnesota","Median income: $66,068","Income needed if you’re a homeowner: $86,546.52","Income needed if you’re a renter: $59,666.52"
22,29,"Nashville, Tennessee","Median income: $62,087","Income needed if you’re a homeowner: $108,095.81","Income needed if you’re a renter: $84,935.81"
23,30,"New Orleans, Louisiana","Median income: $43,258","Income needed if you’re a homeowner: $79,515.42","Income needed if you’re a renter: $63,555.42"
24,33,"Oklahoma City, Oklahoma","Median income: $56,456","Income needed if you’re a homeowner: $59,019.10","Income needed if you’re a renter: $62,691.10"
25,34,"Omaha, Nebraska","Median income: $62,213","Income needed if you’re a homeowner: $79,736.46","Income needed if you’re a renter: $78,680.46"
26,35,"Philadelphia, Pennsylvania","Median income: $49,127","Income needed if you’re a homeowner: $105,641.63","Income needed if you’re a renter: $66,713.63"
27,36,"Phoenix, Arizona","Median income: $60,914","Income needed if you’re a homeowner: $72,816.33","Income needed if you’re a renter: $71,280.33"
28,38,"Raleigh, North Carolina","Median income: $69,720","Income needed if you’re a homeowner: $106,104.82","Income needed if you’re a renter: $72,000.82"
29,40,"San Antonio, Texas","Median income: $53,420","Income needed if you’re a homeowner: $80,437.74","Income needed if you’re a renter: $60,109.74"
30,45,"Tampa, Florida","Median income: $55,634","Income needed if you’re a homeowner: $102,525.56","Income needed if you’re a renter: $69,597.56"
31,46,"Tucson, Arizona","Median income: $45,227","Income needed if you’re a homeowner: $84,669.97","Income needed if you’re a renter: $62,805.97"
32,47,"Tulsa, Oklahoma","Median income: $49,474","Income needed if you’re a homeowner: $64,564.24","Income needed if you’re a renter: $78,916.24"
33,48,"Virginia Beach, Virgina","Median income: $78,136","Income needed if you’re a homeowner: $95,518.17","Income needed if you’re a renter: $76,414.17"
34,49,"Washington, D.C.","Median Income: $90,842","Income needed if you’re a homeowner: $97,458.34","Income needed if you’re a renter: $93,978.34"

In [52]:
#using pandas to inner merge my 2 queries
result = pd.merge(renter_d, d, on=None, how='inner')

In [53]:
#final result
result

,index,city_name,city_median,city_homeowner,city_renter
0,0,"Albuquerque, New Mexico","Median income: $53,936","Income needed if you’re a homeowner: $81,526.74","Income needed if you’re a renter: $65,446.74"
1,6,"Charlotte, North Carolina","Median income: $65,359","Income needed if you’re a homeowner: $98,104.67","Income needed if you’re a renter: $65,992.67"
2,9,"Columbus, Ohio","Median income: $54,902","Income needed if you’re a homeowner: $71,807.21","Income needed if you’re a renter: $71,519.21"
3,10,"Dallas, Texas","Median income: $54,747","Income needed if you’re a homeowner: $87,816.30","Income needed if you’re a renter: $69,216.30"
4,13,"El Paso, Texas","Median income: $48,866","Income needed if you’re a homeowner: $64,270.19","Income needed if you’re a renter: $70,270.19"
5,15,"Fresno, California","Median income: $53,368","Income needed if you’re a homeowner: $94,566.58","Income needed if you’re a renter: $70,614.58"
6,16,"Houston, Texas","Median income: $53,600","Income needed if you’re a homeowner: $77,835.84","Income needed if you’re a renter: $63,363.84"
7,17,"Indianapolis, Indiana","Median income: $50,813","Income needed if you’re a homeowner: $67,865.41","Income needed if you’re a renter: $67,889.41"
8,18,"Jacksonville, Florida","Median income: $55,531","Income needed if you’re a homeowner: $84,560.93","Income needed if you’re a renter: $62,696.93"
9,19,"Kansas City, Missouri","Median income: $56,179","Income needed if you’re a homeowner: $70,142.35","Income needed if you’re a renter: $66,446.35"
10,23,"Louisville, Kentucky","Median income: $54,929","Income needed if you’re a homeowner: $69,624.19","Income needed if you’re a renter: $62,832.19"
11,24,"Memphis, Tennessee","Median income: $41,864","Income needed if you’re a homeowner: $58,358.33","Income needed if you’re a renter: $70,430.33"
12,25,"Mesa, Arizona","Median income: $61,640","Income needed if you’re a homeowner: $103,611.43","Income needed if you’re a renter: $72,075.43"
13,27,"Milwaukee, Wisconsin","Median income: $43,125","Income needed if you’re a homeowner: $63,842.13","Income needed if you’re a renter: $59,282.13"
14,28,"Minneapolis, Minnesota","Median income: $66,068","Income needed if you’re a homeowner: $86,546.52","Income needed if you’re a renter: $59,666.52"
15,30,"New Orleans, Louisiana","Median income: $43,258","Income needed if you’re a homeowner: $79,515.42","Income needed if you’re a renter: $63,555.42"
16,33,"Oklahoma City, Oklahoma","Median income: $56,456","Income needed if you’re a homeowner: $59,019.10","Income needed if you’re a renter: $62,691.10"
17,35,"Philadelphia, Pennsylvania","Median income: $49,127","Income needed if you’re a homeowner: $105,641.63","Income needed if you’re a renter: $66,713.63"
18,36,"Phoenix, Arizona","Median income: $60,914","Income needed if you’re a homeowner: $72,816.33","Income needed if you’re a renter: $71,280.33"
19,38,"Raleigh, North Carolina","Median income: $69,720","Income needed if you’re a homeowner: $106,104.82","Income needed if you’re a renter: $72,000.82"
20,40,"San Antonio, Texas","Median income: $53,420","Income needed if you’re a homeowner: $80,437.74","Income needed if you’re a renter: $60,109.74"
21,45,"Tampa, Florida","Median income: $55,634","Income needed if you’re a homeowner: $102,525.56","Income needed if you’re a renter: $69,597.56"
22,46,"Tucson, Arizona","Median income: $45,227","Income needed if you’re a homeowner: $84,669.97","Income needed if you’re a renter: $62,805.97"